# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - shopershopy-back

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_d0f7c0473b0e4e6798d258c721d84686 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1184f3db697941aaa9386041f3c11863 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d0f7c0473b0e4e6798d258c721d84686 }}/wojtbart/scala:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'shopershopy-back'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0850f47a5f0b4690b382a5e82b2cd989 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d0f7c0473b0e4e6798d258c721d84686 }}/wojtbart/scala:${{ github.sha }}'