# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - shoperrr

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_c93f6b85d2914e93a5d1385f6f2a2922 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c8f72672a454411a82b40dfe056247dd }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c93f6b85d2914e93a5d1385f6f2a2922 }}/wojtbart/react_app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'shoperrr'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7a40265e8bdf4ee384b2db894e2438a7 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c93f6b85d2914e93a5d1385f6f2a2922 }}/wojtbart/react_app:${{ github.sha }}'